server:
  port: 8090

spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local
    include: secret

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
#  data:
#    redis:
#      host: localhost
#      port: 6379

logging:
  level:
    root: info
    com.likelion.culture_test: DEBUG


fastapi:
  base-url: http://localhost:8000
